/**
 * Calendar Utilities for Examora
 * Generates Google Calendar web URLs and downloadable .ics (iCalendar) files for exams.
 */

interface ExamCalendarPayload {
  exam_title?: string;
  exam_date?: string;
  reporting_time?: string;
  safe_departure_time?: string;
  center_name?: string;
  center_address?: string;
  center?: string;
  required_documents?: string[];
  extracted_instructions?: string[];
}

function parseDateTimeIso(dateStr?: string, timeStr?: string): Date | null {
  if (!dateStr) return null;
  try {
    const baseDate = new Date(dateStr);
    if (isNaN(baseDate.getTime())) return null;

    if (timeStr) {
      const clean = timeStr.trim().replace(".", ":");
      const ampmMatch = clean.match(/^(\d{1,2}):(\d{2})\s*([AP]M)$/i);
      if (ampmMatch) {
        let hour = parseInt(ampmMatch[1], 10) % 12;
        if (ampmMatch[3].toUpperCase() === "PM") hour += 12;
        baseDate.setHours(hour, parseInt(ampmMatch[2], 10), 0, 0);
        return baseDate;
      }
      const noAmPmMatch = clean.match(/^(\d{1,2}):(\d{2})$/);
      if (noAmPmMatch) {
        baseDate.setHours(parseInt(noAmPmMatch[1], 10), parseInt(noAmPmMatch[2], 10), 0, 0);
        return baseDate;
      }
    }
    return baseDate;
  } catch {
    return null;
  }
}

function formatToUtcBasic(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    date.getUTCFullYear() +
    pad(date.getUTCMonth() + 1) +
    pad(date.getUTCDate()) +
    "T" +
    pad(date.getUTCHours()) +
    pad(date.getUTCMinutes()) +
    pad(date.getUTCSeconds()) +
    "Z"
  );
}

function buildEventDetails(exam: ExamCalendarPayload): string {
  const lines: string[] = [];
  lines.push(`🎓 Exam: ${exam.exam_title || "Examora Exam"}`);
  if (exam.reporting_time) lines.push(`⏰ Gate Reporting Time: ${exam.reporting_time}`);
  if (exam.safe_departure_time) lines.push(`🚗 Recommended Departure Time: ${exam.safe_departure_time}`);
  
  const locationStr = exam.center_address || exam.center_name || exam.center;
  if (locationStr) lines.push(`📍 Test Centre: ${locationStr}`);

  if (exam.required_documents && exam.required_documents.length > 0) {
    lines.push("\n📋 Required Document Checklist:");
    exam.required_documents.forEach((doc) => lines.push(`  • ${doc}`));
  }

  lines.push("\nGenerated by Examora - Smart Exam Logistics Assistant");
  return lines.join("\n");
}

/**
 * Generates a 1-click Google Calendar web event URL
 */
export function generateGoogleCalendarUrl(exam: ExamCalendarPayload): string {
  const startDate = parseDateTimeIso(exam.exam_date, exam.safe_departure_time || exam.reporting_time) || new Date();
  const endDate = new Date(startDate.getTime() + 3 * 60 * 60 * 1000); // 3 hour default duration

  const title = encodeURIComponent(`Examora: ${exam.exam_title || "Upcoming Exam"}`);
  const details = encodeURIComponent(buildEventDetails(exam));
  const location = encodeURIComponent(exam.center_address || exam.center_name || exam.center || "");
  const dates = `${formatToUtcBasic(startDate)}/${formatToUtcBasic(endDate)}`;

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dates}&details=${details}&location=${location}`;
}

/**
 * Downloads a standard .ics iCalendar file for Apple Calendar, Outlook, and system calendars
 */
export function downloadIcsFile(exam: ExamCalendarPayload): void {
  const startDate = parseDateTimeIso(exam.exam_date, exam.safe_departure_time || exam.reporting_time) || new Date();
  const endDate = new Date(startDate.getTime() + 3 * 60 * 60 * 1000);

  const title = exam.exam_title || "Upcoming Exam";
  const location = exam.center_address || exam.center_name || exam.center || "";
  const description = buildEventDetails(exam).replace(/\n/g, "\\n");

  const icsContent = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Examora//Exam Logistics Assistant//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "BEGIN:VEVENT",
    `SUMMARY:Examora: ${title}`,
    `DESCRIPTION:${description}`,
    `LOCATION:${location}`,
    `DTSTART:${formatToUtcBasic(startDate)}`,
    `DTEND:${formatToUtcBasic(endDate)}`,
    "BEGIN:VALARM",
    "TRIGGER:-PT60M",
    "ACTION:DISPLAY",
    "DESCRIPTION:Time to prepare for your exam!",
    "END:VALARM",
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n");

  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `${(title || "exam").toLowerCase().replace(/[^a-z0-9]/g, "_")}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
